### ISSUE TITLE
readable values 

### ISSUE THREAD

**Issue by MostafaSlaam** [eltonvs/kotlin-obd-api#15]
how to make values of Vehicle Speed readable values 
Vehicle Speed="1091308888Km/h" !!

**Comment by cliffgr** [comment]
I have that issue too.. Seems that the sdk have bug...

**Comment by elip-OE** [comment]
@MostafaSlaam @cliffgr 
I had the same issue with my ELM327 device ([image from amazon](https://m.media-amazon.com/images/I/519t0N2WZqL._AC_.jpg)). I've the reply was different from what the api expected. still, I've created my own version of `SpeedCommand`, and got accurate speed.

```
class MySpeedCommand : ObdCommand() {
    override val tag = "SPEED"
    override val name = "Vehicle Speed"
    override val mode = "01"
    override val pid = "0D"

    override val defaultUnit = "Km/h"
    override val handler = { it: ObdRawResponse -> it.bufferedValue[4].toString() }
}
```

**Comment by cliffgr** [comment]
Great let me check it. But about the other commands :(

**Comment by elip-OE** [comment]
@cliffgr. my guess you will need to do the same for each command. the `bytesToInt` command expect the 8 bytes you recive from the OBD to be a single `Long` which is apparently what the developer's device is giving (my guess it is more of little endian / big endian thingy, but I don't really know)

I case you need only several commands to work with, I suggest to implement each command by yourself. use [this wiki page](https://en.wikipedia.org/wiki/OBD-II_PIDs#Service_01_-_Show_current_data) in order to understand the raw output better.

At least, this is what I'm going to do on my project.

**Comment by eltonvs** [comment]
Thanks for sharing your solution @elip-OE.
You're right about the `bytesToInt` function, I added the tests to this command not taking into consideration there can be some residual value (noise) coming from the OBD device, and just the first byte should be used for the calculation.

I'll try to come up with a solution for the `bytesToInt` function to add a limit of bytes to be used, so I can update the existing commands with this issue.

**Comment by eltonvs** [comment]
Hey!

Version [1.2.0](https://github.com/eltonvs/kotlin-obd-api/releases/tag/v1.1.2) was just released and it should fix this issue.
